import {Ballot,Candidate,ElectionResult,VotingSystemId,VotingRound} from '../types/game';import {systemInfo} from '../data/votingSystems';import {approvalCounts,avgScores,firstCounts,metrics,pairwise,tiebreak} from './metrics';
const tieMessage='There was a tie. The forest used its tie-break rule, which was explained before the election.';
const result=(id:VotingSystemId,w:string,rounds:VotingRound[],counts:Record<string,number>,ballots:Ballot[],cands:Candidate[],why:string,extra:any={}):ElectionResult=>{const info=systemInfo[id];return{systemId:id,systemName:info.name,winnerIds:[w],winnerLabel:cands.find(c=>c.id===w)?.name||w,rounds,counts,explanationForKids:info.short,strengths:info.strengths,weaknesses:info.weaknesses,metrics:metrics(ballots,cands),why,difficulty:info.difficulty,...extra}}
function maxWin(counts:Record<string,number>,ballots:Ballot[],cands:Candidate[]){const max=Math.max(...Object.values(counts));const tied=Object.keys(counts).filter(k=>counts[k]===max);return{win:tied.length>1?tiebreak(tied,ballots,cands):tied[0],tie:tied.length>1}}
function minLose(counts:Record<string,number>,ballots:Ballot[],cands:Candidate[]){const min=Math.min(...Object.values(counts));const tied=Object.keys(counts).filter(k=>counts[k]===min);if(tied.length===1)return{lose:tied[0],tie:false};const protectedWinner=tiebreak(tied,ballots,cands);const lose=[...tied].filter(id=>id!==protectedWinner).sort()[0]||protectedWinner;return{lose,tie:true}}
const withTie=(tie:boolean)=>tie?{tieBreakInfo:tieMessage}:{};
export function runVoting(id:VotingSystemId,ballots:Ballot[],cands:Candidate[]):ElectionResult{if(id==='plurality'){const c=firstCounts(ballots,cands),m=maxWin(c,ballots,cands);return result(id,m.win,[{name:'First-choice count',counts:c,note:'Only the top name on each ballot counts.'}],c,ballots,cands,'This candidate had the most first-choice fans.',withTie(m.tie))}
if(id==='approval'){const c=approvalCounts(ballots,cands),m=maxWin(c,ballots,cands);return result(id,m.win,[{name:'Smile sticker count',counts:c,note:'Every approved candidate gets one smile sticker.'}],c,ballots,cands,'This candidate was acceptable to the most voters.',withTie(m.tie))}
if(id==='score'){const c:Record<string,number>={};cands.forEach(x=>c[x.id]=ballots.reduce((s,b)=>s+(b.scores[x.id]||0),0));const m=maxWin(c,ballots,cands);return result(id,m.win,[{name:'Star total',counts:c,note:'All 0–5 star ratings are added.'}],c,ballots,cands,'This candidate received the most total stars.',withTie(m.tie))}
if(id==='borda'){const n=cands.length,c:Record<string,number>=Object.fromEntries(cands.map(x=>[x.id,0]));ballots.forEach(b=>b.ranking.forEach((cid,i)=>c[cid]+=n-1-i));const m=maxWin(c,ballots,cands);return result(id,m.win,[{name:'Ranking points',counts:c,note:'Higher rankings earn more points.'}],c,ballots,cands,'This candidate was ranked well by many voters.',withTie(m.tie))}
if(id==='runoff'){const first=firstCounts(ballots,cands),top=Object.keys(first).sort((a,b)=>first[b]-first[a]||a.localeCompare(b)).slice(0,2);let second=Object.fromEntries(top.map(x=>[x,0]));ballots.forEach(b=>{const choice=[...top].sort((x,y)=>b.ranking.indexOf(x)-b.ranking.indexOf(y))[0];second[choice]++});const m=maxWin(second,ballots,cands);return result(id,m.win,[{name:'First round',counts:first,note:'The two largest baskets become finalists.',finalists:top},{name:'Final round',counts:second,note:'Each ballot goes to the finalist ranked higher.'}],second,ballots,cands,'This candidate beat the other finalist in the second round.',withTie(m.tie))}
if(id==='irv'){let active=cands.map(c=>c.id),rounds:VotingRound[]=[],tie=false;while(active.length>1){let c=Object.fromEntries(active.map(x=>[x,0]));ballots.forEach(b=>{const x=b.ranking.find(r=>active.includes(r));if(x)c[x]++});const maj=Object.keys(c).find(k=>c[k]>ballots.length/2);if(maj)return result(id,maj,rounds.concat({name:`Round ${rounds.length+1}`,counts:c,note:'A candidate has more than half of active votes.'}),c,ballots,cands,'This candidate reached a majority after lower candidates were removed.',withTie(tie));const m=minLose(c,ballots,cands);tie=tie||m.tie;rounds.push({name:`Round ${rounds.length+1}`,counts:c,note:`${cands.find(x=>x.id===m.lose)?.name} has the fewest votes and leaves the race. Ballots for that animal move to the next ranked candidate who is still active.`,eliminatedId:m.lose});active=active.filter(x=>x!==m.lose)}return result(id,active[0],rounds,{},ballots,cands,'This was the last remaining candidate.',withTie(tie))}
if(id==='star'){const totals:Record<string,number>={};cands.forEach(x=>totals[x.id]=ballots.reduce((s,b)=>s+(b.scores[x.id]||0),0));const top=Object.keys(totals).sort((a,b)=>totals[b]-totals[a]||a.localeCompare(b)).slice(0,2);const run=Object.fromEntries(top.map(x=>[x,0]));ballots.forEach(b=>{const [a,bid]=top;if((b.scores[a]||0)>(b.scores[bid]||0))run[a]++;else if((b.scores[bid]||0)>(b.scores[a]||0))run[bid]++});const m=maxWin(run,ballots,cands);return result(id,m.win,[{name:'Score round',counts:totals,note:'Top two star totals become finalists.',finalists:top},{name:'Automatic runoff',counts:run,note:'Each ballot supports the finalist it scored higher. Equal scores count as no preference.'}],run,ballots,cands,'This finalist was preferred on more ballots after the star count.',withTie(m.tie))}
if(id==='condorcet'){const m=pairwise(ballots,cands),scores:Record<string,number>={};let cw='';cands.forEach(a=>{scores[a.id]=0;cands.forEach(b=>{if(a.id!==b.id){if(m[a.id][b.id]>m[b.id][a.id])scores[a.id]++;else if(m[a.id][b.id]<m[b.id][a.id])scores[a.id]--}});if(scores[a.id]===cands.length-1)cw=a.id});const mw=maxWin(scores,ballots,cands),win=cw||mw.win;return result(id,win,[{name:'Friendly matchups',counts:scores,note:cw?'One animal beat every other animal one-on-one.':'No single animal beat every other animal one-on-one. This is called a cycle. Copeland fallback winner is used.'}],scores,ballots,cands,cw?'This candidate beat every other candidate one-on-one.':'No Condorcet winner appeared, so the Copeland fallback was used.',{matrix:m,...withTie(!cw&&mw.tie)})}
const votes=firstCounts(ballots,cands),seats:Record<string,number>=Object.fromEntries(cands.map(c=>[c.id,0]));for(let s=0;s<7;s++){const win=Object.keys(votes).sort((a,b)=>votes[b]/(seats[b]+1)-votes[a]/(seats[a]+1)||a.localeCompare(b))[0];seats[win]++}const leader=Object.keys(seats).sort((a,b)=>seats[b]-seats[a]||votes[b]-votes[a]||a.localeCompare(b))[0];return result('council',leader,[{name:'Seven council seats',counts:seats,note:'Seats are assigned one at a time using D’Hondt: first-choice votes divided by seats already won plus one.'}],seats,ballots,cands,'This is a council, so several candidates can win seats.',{seats})}
export const runAll=(ids:VotingSystemId[],ballots:Ballot[],cands:Candidate[])=>ids.map(id=>runVoting(id,ballots,cands));
